name: Swift Build and Test in DevContainer
on:
  push:
  pull_request:

jobs:
  build:
    name: Swift on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Docker (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install --cask docker || brew upgrade --cask docker
        open -g -a Docker.app && sleep 60

    - name: Build and Test in DevContainer
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: |
          swift build -Xswiftc -strict-concurrency=complete -v
          swift test -c release -Xswiftc -strict-concurrency=complete -v
